<x-app-layout title="Pilot Hotel | Dashboard">
    <header class="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="text-sm font-semibold text-moss">{{ $currentTime->format('l, d F Y') }} · {{ $currentTime->format('h:i A') }} Philippine time</p><h1 class="mt-2 text-4xl font-semibold">Good {{ $currentTime->hour < 12 ? 'morning' : ($currentTime->hour < 18 ? 'afternoon' : 'evening') }}, Sofia</h1><p class="mt-2 text-stone-500">Here is what is happening across the hotel today.</p></div><a href="{{ route('reservations.index') }}" class="btn-primary self-start">+ New reservation</a></header>
    <section class="mt-10 grid gap-4 md:grid-cols-3">
        @foreach ([['Pending / Confirmed', $stats['arriving'], 'Reservations waiting to check in'], ['Check-ins today', $stats['checkIns'], 'Scheduled for today'], ['Checked-Out', $stats['checkOuts'], 'Completed reservations']] as $stat)
            <article class="rounded-2xl border border-stone-200 bg-white p-6"><p class="text-sm text-stone-500">{{ $stat[0] }}</p><p class="mt-4 font-display text-4xl font-semibold">{{ $stat[1] }}</p><p class="mt-2 text-sm text-moss">{{ $stat[2] }}</p></article>
        @endforeach
    </section>
    <section class="mt-8 rounded-2xl border border-stone-200 bg-white p-6"><div class="flex items-center justify-between"><h2 class="text-xl font-semibold">Recent reservations</h2><a href="{{ route('reservations.index') }}" class="text-sm font-semibold text-moss">View all →</a></div><div class="mt-5 overflow-x-auto"><table class="w-full min-w-[620px] text-left text-sm"><thead class="border-b border-stone-100 text-xs uppercase tracking-wider text-stone-400"><tr><th class="pb-3">Guest</th><th class="pb-3">Room</th><th class="pb-3">Stay</th><th class="pb-3">Status</th><th class="pb-3 text-right">Amount</th></tr></thead><tbody>@foreach ($reservations as $reservation)<tr class="border-b border-stone-100 last:border-0"><td class="py-4 font-semibold">{{ $reservation->guest_name }}<div class="text-xs font-normal text-stone-400">{{ $reservation->code }}</div></td><td class="py-4">{{ $reservation->room }}</td><td class="py-4">{{ $reservation->check_in->format('d M') }} – {{ $reservation->check_out->format('d M') }}</td><td class="py-4"><span class="status-pill status-{{ str($reservation->status)->lower()->replace(' ', '-') }}">{{ $reservation->status }}</span></td><td class="py-4 text-right font-semibold">₱{{ number_format($reservation->amount, 2) }}</td></tr>@endforeach</tbody></table></div></section>
</x-app-layout>
