<x-app-layout title="Pilot Hotel | Reports">
    <header class="flex flex-col justify-between gap-5 xl:flex-row xl:items-end">
        <div><p class="text-sm font-semibold text-moss">Operational and financial intelligence</p><h1 class="mt-2 text-4xl font-semibold">Reports</h1><p class="mt-2 text-sm text-stone-500">Generated {{ now()->format('d M Y, h:i A') }}</p></div>
        <div class="flex flex-wrap gap-3"><a class="btn-secondary" target="_blank" href="{{ route('reports.print', request()->query()) }}">Print Report</a><a class="btn-secondary" href="{{ route('reports.print', request()->query()) }}" onclick="window.open(this.href, '_blank'); return false;">Export PDF</a><a class="btn-primary" href="{{ route('reports.export.excel', request()->query()) }}">Export Excel</a></div>
    </header>
    <section class="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">
        @foreach ([['Total Reservations', $summary['reservations']], ['Today\'s Check-Ins', $summary['check_ins']], ['Today\'s Check-Outs', $summary['check_outs']], ['No-Shows', $summary['no_shows']], ['Cancelled', $summary['cancelled']], ['Today\'s Revenue', '₱'.number_format($summary['revenue'], 2)]] as $card)
            <div class="rounded-2xl border border-stone-200 bg-white p-5"><p class="text-xs font-semibold uppercase tracking-wider text-stone-400">{{ $card[0] }}</p><p class="mt-3 text-2xl font-semibold">{{ $card[1] }}</p></div>
        @endforeach
    </section>
    <form class="mt-8 grid gap-3 rounded-2xl border border-stone-200 bg-white p-5 md:grid-cols-6 md:items-end" method="get">
        <div><label class="text-xs font-bold uppercase tracking-wider text-stone-400" for="report">Report</label><select class="field" id="report" name="report"><option value="reservations" @selected($reportType === 'reservations')>Reservation Report</option><option value="check-ins" @selected($reportType === 'check-ins')>Check-In Report</option><option value="check-outs" @selected($reportType === 'check-outs')>Check-Out Report</option><option value="no-shows" @selected($reportType === 'no-shows')>No-Show Report</option><option value="cancellations" @selected($reportType === 'cancellations')>Cancellation Report</option><option value="revenue" @selected($reportType === 'revenue')>Revenue Report</option><option value="occupancy" @selected($reportType === 'occupancy')>Room Occupancy</option></select></div>
        <div><label class="text-xs font-bold uppercase tracking-wider text-stone-400" for="period">Date range</label><select class="field" id="period" name="period"><option value="today" @selected($filters['preset'] === 'today')>Today</option><option value="yesterday" @selected($filters['preset'] === 'yesterday')>Yesterday</option><option value="week" @selected($filters['preset'] === 'week')>This Week</option><option value="month" @selected($filters['preset'] === 'month')>This Month</option><option value="custom" @selected($filters['preset'] === 'custom')>Custom Date Range</option></select></div>
        <div><label class="text-xs font-bold uppercase tracking-wider text-stone-400" for="from">From</label><input class="field" id="from" name="from" type="date" value="{{ $filters['from']->format('Y-m-d') }}"></div><div><label class="text-xs font-bold uppercase tracking-wider text-stone-400" for="to">To</label><input class="field" id="to" name="to" type="date" value="{{ $filters['to']->format('Y-m-d') }}"></div>
        <div><label class="text-xs font-bold uppercase tracking-wider text-stone-400" for="search">Search</label><input class="field" id="search" name="search" value="{{ $filters['search'] }}" placeholder="Guest, ID, room"></div><button class="btn-primary" type="submit">Generate Report</button>
        <div class="md:col-span-6 grid gap-3 sm:grid-cols-3"><div><label class="text-xs font-bold uppercase tracking-wider text-stone-400" for="status">Reservation status</label><select class="field" id="status" name="status"><option value="">All statuses</option>@foreach (\App\Models\Reservation::STATUSES as $status)<option value="{{ $status }}" @selected($filters['status'] === $status)>{{ $status }}</option>@endforeach</select></div><div><label class="text-xs font-bold uppercase tracking-wider text-stone-400" for="payment_status">Payment status</label><select class="field" id="payment_status" name="payment_status"><option value="">All payment statuses</option>@foreach (['unpaid', 'paid', 'retained', 'refunded', 'partially-retained'] as $status)<option value="{{ $status }}" @selected($filters['payment_status'] === $status)>{{ str($status)->replace('-', ' ')->title() }}</option>@endforeach</select></div><div><label class="text-xs font-bold uppercase tracking-wider text-stone-400" for="payment_method">Payment method</label><select class="field" id="payment_method" name="payment_method"><option value="">All payment methods</option>@foreach (['Cash', 'Card', 'Bank Transfer', 'E-Wallet'] as $method)<option value="{{ $method }}" @selected($filters['payment_method'] === $method)>{{ $method }}</option>@endforeach</select></div></div>
    </form>
    <section class="mt-8 rounded-2xl border border-stone-200 bg-white p-5 sm:p-6">
        <div class="flex items-center justify-between gap-3"><div><p class="text-sm font-semibold text-moss">{{ $reportTitle }}</p><h2 class="mt-1 text-2xl font-semibold">{{ $filters['from']->format('d M Y') }} to {{ $filters['to']->format('d M Y') }}</h2></div><span class="text-sm text-stone-500">{{ $reservations->count() }} record(s)</span></div>
        @if ($reportType === 'occupancy')
            <div class="mt-6 grid gap-3 sm:grid-cols-4">@foreach ([['Total Rooms', $occupancy['total']], ['Available', $occupancy['available']], ['Reserved', $occupancy['reserved']], ['Occupancy Rate', $occupancy['rate'].'%']] as $card)<div class="rounded-xl bg-stone-50 p-4"><p class="text-xs uppercase tracking-wider text-stone-400">{{ $card[0] }}</p><p class="mt-2 text-xl font-semibold">{{ $card[1] }}</p></div>@endforeach</div><div class="mt-6 overflow-x-auto"><table class="w-full text-left text-sm"><thead class="text-xs uppercase tracking-wider text-stone-400"><tr><th class="p-3">Room</th><th class="p-3">Room Type</th><th class="p-3">Current Status</th></tr></thead><tbody>@foreach ($occupancy['rooms'] as $room)<tr class="border-t border-stone-100"><td class="p-3 font-semibold">{{ $room['number'] }}</td><td class="p-3">{{ $room['type'] }}</td><td class="p-3"><span class="status-pill {{ $room['status'] === 'Available' ? 'status-checked-in' : 'status-confirmed' }}">{{ $room['status'] }}</span></td></tr>@endforeach</tbody></table></div>
        @elseif ($reportType === 'revenue')
            <div class="mt-6 grid gap-3 sm:grid-cols-3">@foreach ([['Room Revenue', $revenue['room']], ['Additional Charges', $revenue['additional']], ['Discounts', $revenue['discounts']], ['Refunds', $revenue['refunds']], ['Total Collected', $revenue['collected']], ['Outstanding Balance', $revenue['outstanding']]] as $card)<div class="rounded-xl bg-stone-50 p-4"><p class="text-xs uppercase tracking-wider text-stone-400">{{ $card[0] }}</p><p class="mt-2 text-xl font-semibold">₱{{ number_format($card[1], 2) }}</p></div>@endforeach</div>
        @else
            <div class="mt-6 overflow-x-auto"><table class="w-full min-w-[1250px] text-left text-sm"><thead class="bg-stone-50 text-xs uppercase tracking-wider text-stone-400"><tr><th class="p-3">Reservation ID</th><th class="p-3">Guest / Contact</th><th class="p-3">Room / Type</th><th class="p-3">Guests</th><th class="p-3">Booking Date</th><th class="p-3">Check-In</th><th class="p-3">Check-Out</th><th class="p-3">Total</th><th class="p-3">Paid / Balance</th><th class="p-3">Payment</th><th class="p-3">Status</th><th class="p-3">Staff / Remarks</th></tr></thead><tbody>@forelse ($reservations as $reservation)<tr class="border-t border-stone-100 align-top"><td class="p-3 font-semibold text-moss">{{ $reservation->code }}</td><td class="p-3">{{ $reservation->guest_name }}<div class="text-xs text-stone-400">{{ $reservation->guest_phone ?: 'No phone' }}</div></td><td class="p-3">{{ $reservation->room }}<div class="text-xs text-stone-400">{{ $reservation->room_type }}</div></td><td class="p-3">{{ $reservation->adults + $reservation->children }}</td><td class="p-3">{{ $reservation->created_at?->format('d M Y') }}</td><td class="p-3">{{ $reservation->check_in->format('d M Y') }}<div class="text-xs text-stone-400">{{ $reservation->checked_in_at?->format('h:i A') ?: '2:00 PM' }}</div></td><td class="p-3">{{ $reservation->check_out->format('d M Y') }}<div class="text-xs text-stone-400">{{ $reservation->checked_out_at?->format('h:i A') ?: '11:00 AM' }}</div></td><td class="p-3 font-semibold">₱{{ number_format($reservation->total_amount, 2) }}</td><td class="p-3">₱{{ number_format($reservation->amount_paid, 2) }}<div class="text-xs text-stone-400">₱{{ number_format($reservation->balance, 2) }} due</div></td><td class="p-3">{{ $reservation->payment_status }}<div class="text-xs text-stone-400">{{ $reservation->payment_method ?: 'Not set' }}</div></td><td class="p-3"><span class="status-pill status-{{ str($reservation->status)->lower()->replace(' ', '-') }}">{{ $reservation->status }}</span></td><td class="p-3">{{ $reservation->staff_name }}<div class="max-w-[160px] text-xs text-stone-400">{{ $reservation->remarks ?: $reservation->no_show_remarks ?: 'No remarks' }}</div></td></tr>@empty<tr><td colspan="12" class="p-10 text-center text-stone-500">No records match these filters.</td></tr>@endforelse</tbody></table></div>
        @endif
    </section>
</x-app-layout>